#pragma kernel CSMain

RWTexture2D<float4> Texture;
float LuminanceResolution;
RWStructuredBuffer<int> Result;

[numthreads(16,16,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    // InterlockedAdd can only be used with integers, this is why we multiply by LuminanceResolution
    InterlockedAdd(Result[0], LuminanceResolution * (
        round(Texture[id.xy].r * 100.) * 100 +
        round(Texture[id.xy].g * 100.) * 1 +
        round(Texture[id.xy].b * 100.) * .01
    ));
}