name: Actions

env:
  BUILD_NAME: NORDARK-WP5

on:
  push:
    tags:        
      - '*'

jobs:
  build:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneOSX
          - StandaloneWindows64
          - StandaloneLinux64

    steps:
      - name: Free disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-

      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          versioning: Semantic
          buildsPath: '.'
          buildName: ${{ env.BUILD_NAME }}

      - name: sqlite3 fix
        if: matrix.targetPlatform == 'StandaloneWindows64'
        run: sudo cp AdditionalResources/sqlite3.dll ${{ matrix.targetPlatform }}/${{ env.BUILD_NAME }}_Data/Plugins/x86_64
          
      - name: Create Zip
        run: zip -r Build-${{ matrix.targetPlatform }}.zip ${{ matrix.targetPlatform }}
        
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: Build-${{ matrix.targetPlatform }}.zip
          draft: false
          prerelease: false
          generate_release_notes: true
